spring:
  application:
    name: Super-ai-agent
  # profiles:
  #   active: ${SPRING_PROFILES_ACTIVE:local}
  ai:
    retry:
      max-attempts: 1
      on-client-errors: false
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_MODEL:qwen3:8b}
        options:
          temperature: 0.7
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: ${DASHSCOPE_MODEL:qwen3-max-2026-01-23}
          temperature: 0.7
      embedding:
        options:
          model: ${DASHSCOPE_EMBEDDING_MODEL:text-embedding-v4}
          dimensions: 1024

# MySQL 数据源配置
  datasource:
    jdbc-url: ${MYSQL_URL:jdbc:mysql://localhost:3306/super_ai_agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

# PGVector 配置
pgvector:
  datasource:
    jdbc-url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/super_ai_agent}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
    initialize-schema: true
  ai:
    vectorstore:
      pgvector:
      # 【核心开关】设置为 true 开启自动建表和扩展
        initialize-schema: true 
        index-type: HNSW
        dimensions: 1024
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
        # 表名配置
        table-name: vector_store
        schema-name: public

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: ${SERVER_PORT:8123}
  servlet:
    context-path: /api
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    # 尝试打开 UI 时是否禁用缓存
    disable-swagger-default-url: true
    # 是否显示操作 ID（用于代码生成）
    display-operation-id: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.monuo.superaiagent.controller
  # 是否展示 Actuator 端点（如果你集成了 actuator）
  show-actuator: true

search-api:
  api-key: ${SEARCH_API_KEY:}
  tavily-api-key: ${TAVILY_SEARCH_API_KEY:}

qq-email:
  from: ${QQ_EMAIL_FROM:}
  auth-code: ${QQ_EMAIL_AUTH_CODE:}
  smtp-host: ${QQ_EMAIL_SMTP_HOST:smtp.qq.com}
  smtp-port: ${QQ_EMAIL_SMTP_PORT:587}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"  # 暴露所有端点（包括 health, info 等）
  endpoint:
    health:
      show-details: always # 显示健康检查的详细信息
